name: Test BloodPressureDLL Package (推定まで)

on:
  workflow_dispatch:

jobs:
  test-package:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Prepare test directory
        run: |
          mkdir test_env
          xcopy /E /I /Y CppBloodPressureDLL\package test_env\
          xcopy /E /I /Y sample-data test_env\sample-data
        shell: cmd

      - name: List test_env contents
        run: |
          dir test_env
          dir test_env\models
          dir test_env\sample-data
        shell: cmd

      - name: Copy TestApp.csproj and Program.cs.template
        run: |
          copy TestApp.csproj test_env\TestApp.csproj
          copy Program.cs.template test_env\Program.cs
        shell: cmd

      - name: Build C# test app
        run: |
          cd test_env
          dotnet build -c Release -p:Platform=x64
        shell: cmd

      - name: Run C# BP estimation test app
        run: |
          cd test_env
          set PATH=%CD%;%PATH%
          dotnet run -c Release -p:Platform=x64
        shell: cmd

      - name: Install Visual C++ Redistributable
        run: |
          choco install vcredist140 -y
        shell: cmd
